server:
  port: 8082
spring:
  application:
    name: service-user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.69.98:13306/db_ershouche?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: db_ershouche
    password: 7696d98623
    # Redis的相关配置
  data:
    redis:
      host: 47.97.69.98
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.69.98:8848
# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
aliyun:
  message:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    appcode: 29e278ebb47148d39bd78cdb62a09169