# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.80.129:3307/db_qixing?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/db_qixing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: toor
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379
#  password: 123456

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
spzx:
  auth:
    list:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      #- /admin/system/category/download 下载

      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /v3/api-docs/**
  minio:
    endpoint: http://127.0.0.1:9000
    user: minioadmin
    password: minioadmin
    bucket: zmts-bucket