server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: toor
    # Redis的相关配置
    data:
      redis:
        host: localhost
        port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml