server:
  port: 8083
spring:
  application:
    name: service-cart
    # 不需要查mysql数据库 直接查redis
    # Redis的相关配置
  data:
    redis:
      host: 47.97.69.98
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.69.98:8848
