server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.69.98:13306/db_qixing?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: db_qixing
    password: 71467424d1
    # Redis的相关配置
    data:
      redis:
        host: 47.97.69.98
        port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.69.98:8848
# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml